name: Release
on:
  workflow_run:
    workflows: [Build and test]
    types: [completed]
    branches: [main]

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - uses: fregante/setup-git-user@v1
      - name: Bump Version
        uses: qzb/standard-version-action@v1.0.5
      - name: Push changelogs
        run: |
          git push --follow-tags origin main