name: Release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
      - run: npm ci
      - uses: fregante/setup-git-user@v1
      - name: Bump version and push changelogs
        run: |
          npm run release
          git push origin main --follow-tags