name: Release
on:
  workflow_run:
    workflows: [Build and test]
    types: [completed]
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - name: Configure committer
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Bump Version
        uses: qzb/standard-version-action@v1.0.5